#!/bin/sh
#

export black="\[\033[1;38;5;0m\]"
export red="\[\033[1;38;5;1m\]"
export orange="\[\033[1;38;5;130m\]"
export green="\[\033[1;38;5;2m\]"
export yellow="\[\033[1;38;5;3m\]"
export blue="\[\033[1;38;5;4m\]"
export bblue="\[\033[1;38;5;12m\]"
export magenta="\[\033[1;38;5;55m\]"
export cyan="\[\033[1;38;5;6m\]"
export white="\[\033[1;38;5;7m\]"
export coldblue="\[\033[1;38;5;33m\]"
export smoothblue="\[\033[1;38;5;111m\]"
export iceblue="\[\033[1;38;5;45m\]"
export turqoise="\[\033[1;38;5;50m\]"
export smoothgreen="\[\033[1;38;5;42m\]"
export defaultcolor="\e[0m"

PS1="${yellow}#\# ${red}\u@lazylady${white}-\A${blue} \w ${green}\$ ${defaultcolor}"
